#  Template React Deploy

# For advanced cases, please, follow examples from the pipe's:
# README https://bitbucket.org/atlassian/aws-s3-deploy/src/master/README.md
# README https://bitbucket.org/atlassian/aws-cloudfront-invalidate/src/master/README.md

image: node:16

# Workflow Configuration

pipelines:
  branches:
    develop:
      - parallel:
          - step:
              name: Install
              caches:
                - node
              script:
                - yarn install
          -step:
            name: Build
            script:
                - yarn run build
                - REACT_APP_ENV:$ENV
                - REACT_APP_SENTRY_DSN:$ENV_SENTRY_DSN
                - REACT_APP_42EVENT_API_URL:$ENV_42EVENT_API_URL
              artifacts:
                - build/**
      - step:
          name: Deploy to S3 & Invalidate Cloudfront Cache
          deployment: Production
          clone:
            enabled: false
          script:
            # sync your files to S3
            - pipe: atlassian/aws-s3-deploy:1.1.0
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                S3_BUCKET: $S3_BUCKET
                LOCAL_PATH: 'build'
            # triggering a distribution invalidation to refresh the CDN caches
            - pipe: atlassian/aws-cloudfront-invalidate:0.6.0
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                DISTRIBUTION_ID: E3KT2Y6GIA2R59
